"""Create deterministic procedural RGB-D data, without third-party dataset assets."""

import argparse
import csv
from pathlib import Path

import numpy as np
from PIL import Image

from .io import new_directory, write_json


def create_demo(output):
    output = new_directory(output)
    y, x = np.mgrid[:112, :140]
    rows = []
    for i in range(3):
        pattern = (30 + (x * (3 + i) + y * 2) % 190).astype(np.uint8)
        circle = (x - 65 - i * 5) ** 2 + (y - 56) ** 2 < (20 + i * 3) ** 2
        image = np.stack((pattern, np.roll(pattern, 8, 0), np.roll(pattern, 12, 1)), axis=-1)
        image[circle] = [220, 170, 90]
        depth = np.full((112, 140), 0.9 + 0.03 * i, np.float32)
        depth[circle] = 0.35 + 0.05 * i
        id_ = f"scene_{i:02d}"
        Image.fromarray(image).save(output / f"{id_}.png")
        np.save(output / f"{id_}.npy", depth)
        rows.append(dict(id=id_, rgb=f"{id_}.png", depth=f"{id_}.npy"))
    with (output / "rgbd.csv").open("x", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=["id", "rgb", "depth"])
        writer.writeheader()
        writer.writerows(rows)
    write_json(
        output / "provenance.json",
        dict(
            source="procedurally generated by demo.py",
            purpose="software smoke tests; not a benchmark",
            depth_units="meters",
        ),
    )
    return output / "rgbd.csv"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    print(create_demo(parser.parse_args().output))


if __name__ == "__main__":
    main()
